spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/remindly
spring.datasource.username=root
spring.datasource.password=abcd@1234..

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true